### ISSUE TITLE
[META] Blockers for experimental release

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#29]
Let's use this issue to track blockers for our initial release (v0.1.0)

- [x] Bring testing up to release quality https://github.com/elastic/elastic-synthetics/issues/25
- [x] Add CI jobs to ensure tests / linters run before all merges
- [x] Add LICENSE file and Linter tooling to ensure headers #100 
- [x] Add minimal docs
- [x] Screenshot on failure https://github.com/elastic/synthetics/issues/73
- [x] Fix `--headless` flag https://github.com/elastic/elastic-synthetics/issues/30 PR: https://github.com/elastic/elastic-synthetics/pull/39
- [x] Make the repo public
- [x] Examples structure defined and working: https://github.com/elastic/synthetics/issues/95
- [x] Journey start/end timestamps are incorrect https://github.com/elastic/synthetics/issues/118
- [x] publish version 0.0.1 ~~without alpha tags~~ (leaving the alpha tags to clearify that this is experimental)

**Comment by paulb-elastic** [comment]
We have agreed to leave the alpha tags on the npm package, so it's clear that this is experimental, and everything could potentially change.  The package can be found here: https://www.npmjs.com/package/@elastic/synthetics

Updating the main description in this issue to reflect this.
