### ISSUE TITLE
[META] Push command

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/synthetics#494]
# Summary

This **META** issue covers the `push` command: a CLI feature which will allow users to push their monitors directly from the CLI to the Elastic Stack.

## High Level Overview

The command would be `elastic-synthetics push`. Invoking it would:

1. Establish a connection to the specified stack's kibana instance
2. Filter local journeys using existing flags to match only those specified
3. Create individual JS bundles per journey using a dependency resolution library
4. Use the monitor management APIs to create a monitor per journey using those zipped JS bundles

Once pushed to Kibana, Heartbeat would be able to download these journeys and execute them.

## Issues

This issue has been broke down into three main parts:

- [x] Agent CLI implementation of the push command (https://github.com/elastic/synthetics/issues/470)
    - [x] DSL Implementation - https://github.com/elastic/synthetics/pull/493
    - [x] Push Implementation - https://github.com/elastic/synthetics/pull/482
- [x] Heartbeat updates to be able to run the pushed journeys - https://github.com/elastic/beats/issues/31363
- [x] Kibana API updates to support the push command - https://github.com/elastic/kibana/issues/127677
    - [x] API Updates for API Keys to include Kibana roles - https://github.com/elastic/kibana/pull/130918
- [x] https://github.com/elastic/synthetics-dev/issues/119
- [x] https://github.com/elastic/synthetics/issues/513
- [ ] ~~https://github.com/elastic/infosec/issues/10478~~ pushed to 8.4

The following changes are also necessary, but out of the main line of work:

- [x] Updating the accepted throttling format for Heartbeat so that the monitor DSL can use it (https://github.com/elastic/beats/issues/31362)

## Docs

- [x] https://github.com/elastic/observability-docs/issues/1906

## Related

* [A previous discussion on the DSL and monitor ontology](https://github.com/elastic/synthetics/issues/451)
* https://github.com/elastic/kibana/issues/123969 (out-of-date, but includes more context)
* Scaffolding a new synthetics project - #502

**Comment by paulb-elastic** [comment]
Added https://github.com/elastic/uptime-dev/issues/96 to the above list

**Comment by shahzad31** [comment]
PR related to API key enhancements needed for push command https://github.com/elastic/kibana/pull/130918

**Comment by paulb-elastic** [comment]
https://github.com/elastic/infosec/issues/10478 has been pushed to 8.4, so closing this meta as all the other activities for getting project monitors (`push`) out for 8.3 in beta form, are done.
