### ISSUE TITLE
Push command final touchup before release 

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#513]
- [x] Update the location list including the beta locations - #515 
- [x] Update the API Keys docs link in the CLI to point to the Uptime APIKey docs (https://github.com/elastic/kibana/pull/134652) - https://github.com/elastic/synthetics/blob/48949329521518784088d1a275c95fc4592fcb0d/src/cli.ts#L171
    Depends on https://github.com/elastic/observability-docs/issues/1906.
- [x] Default monitor config - schedule, locations, throttling etc - #508 
- [ ] Update the banner text for the scaffolding template with relevant push docs - https://github.com/elastic/synthetics/blob/ae26736f34d93d56b9e047e17dcba6e6d1254d0a/src/generator/index.ts#L185 (note the doc link being used in [_Learn more_](https://github.com/elastic/uptime/issues/472) on the API key generation screen, is https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html)

**Comment by lucasfcosta** [comment]
Hey @vigneshshanmugam, can you add more details about the last item in the list?

> Update the banner test for the scaffolding template with relevant push docs.

I'm not entirely sure I understand what this one refers to.

**Comment by vigneshshanmugam** [comment]
Ah, it was a typo - banner text. Relevant on the code here - https://github.com/elastic/synthetics/blob/ae26736f34d93d56b9e047e17dcba6e6d1254d0a/src/generator/index.ts#L198

Basically need to enhance that text and guide the users to the relevant documentation for push and init commands.

**Comment by paulb-elastic** [comment]
Added that the doc link being used in [_Learn more_](https://github.com/elastic/uptime/issues/472) on the API key generation screen, is https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html

**Comment by vigneshshanmugam** [comment]
@paulb-elastic I dont see anything related to the API in the old or the new doc. Am I looking at the wrong place?

**Comment by paulb-elastic** [comment]
> @paulb-elastic I dont see anything related to the API in the old or the new doc. Am I looking at the wrong place?

@vigneshshanmugam the doc updates for the `push` command aren't live yet, still being finalised in https://github.com/elastic/observability-docs/pull/1925, for the 8.3 release

**Comment by vigneshshanmugam** [comment]
@paulb-elastic Sure makes sense - https://github.com/elastic/synthetics/pull/538
