### ISSUE TITLE
[Meta] Synthetics Agent enhancements for Private Node

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/synthetics#557]
To support private node, and enhance the current experience of the project monitors, updates are needed to the synthetics `init` command, `monitor.use` DSL, and `push` command line arguments.

Enhancements to `init`
--
- [ ] The new init command will update the existing questionnaire to the following options. Exact content/phrasing TBD.

* Are you using elastic cloud? Y/N
     Y: What is your cloud.id (You can find this....) ? 
     N: What is the url of your Kibana instance?
* What api key would you like to use for auth? (Include link to Kibana to set up API Key)
* Choosing a default location
     * IF locations are available, user will be able to select froma list of locations that includes both publc (if in cloud), and private locations together, with each location clearly indicating if it's public or private. 
     * IF locations are not available (for example, an on-prem cluster that has not yet set up private locations): A link to docs for how to set up your first private location is displayed
 * Choose default interval
 * Choose project id
 * Choose space
 
DSL experience with `monitor.use`
--
 - [x] Add new key for private locations `privateLocations`
 
`push` command override
--
- [x] Add new --private-locations option to the push command

Locations discovery
--
- [ ] Provide additional discovery for new locations via new synthetics discovery command: https://github.com/elastic/synthetics/issues/551
