### ISSUE TITLE
[META] Synthetics Beta Release

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#61]
### Decision items
- [x] Syntax finalized
- [x] Schema finalized
- [x] Decision on browser (e.g. Chromium) and framework (e.g. Playwright)
- [x] Bundle Synthetics Agent with Heartbeat Docker container https://github.com/elastic/beats/issues/22837

### Other
- [x] Implement more mature packaging strategy elastic/synthetics#140 
- [x] Merge synthetics feature branches into beats mainline https://github.com/elastic/beats/pull/21436
- [x] Add E2E / Functional tests between Heartbeat <-> Synthetics <-> UI https://github.com/elastic/synthetics/issues/115
- [x] Add Functional test for CLI https://github.com/elastic/synthetics/issues/139
- [x] Unit tests for network/waterfall timing calculation https://github.com/elastic/synthetics/issues/185
- [x] Migrate to regular heartbeat docker image https://github.com/elastic/synthetics/issues/182
- [x] Complete docs
  - [x] Docs/release note to make it clear that the latest version of the Synthetic Agent is needed (specifically, to support the waterfall chart)
  - [x] Document package.json for synthetics https://github.com/elastic/observability-docs/issues/284
  - [x] Document how to use/deploy Docker images (not run.sh) https://github.com/elastic/observability-docs/issues/300
- [x] Update notices and banners from experimental to beta https://github.com/elastic/kibana/issues/91421
- [x] Run Playwright post-install script to fix chrome binary sometimes unavailable https://github.com/elastic/synthetics/issues/142
- [x] Feature flag to control filmstrip image capture https://github.com/elastic/synthetics/issues/143
- [x] (Bug) Docker example doesn't work well with uids != 1000 https://github.com/elastic/synthetics/issues/156
- [x] Redirects and DNS failures not represented correctly https://github.com/elastic/synthetics/issues/175
- [x] no-sandbox option 
  - [x] Synthetics implementation https://github.com/elastic/synthetics/issues/136
  - [x] Heartbeat implementation https://github.com/elastic/beats/issues/22901
- [x] Release Synthetics as package version 1.0.0-beta at FF (early enough for BCs)
- [x] Move network info fields to ECS https://github.com/elastic/synthetics/issues/164
- [x] Move timing calculation to agent https://github.com/elastic/synthetics/issues/152
- [x] Exit with non-zero code when any step fails https://github.com/elastic/synthetics/issues/191
- [x] Source is transpiled to lower JS version for suites https://github.com/elastic/synthetics/issues/172
- [x] Plan for handling synthetics dependencies https://github.com/elastic/beats/issues/22928
- [x] Remote Zip URL support for heartbeat synthetics https://github.com/elastic/uptime/issues/271

**Comment by paulb-elastic** [comment]
Some items moved from beta to the [GA](https://github.com/elastic/synthetics/issues/93) phase

**Comment by paulb-elastic** [comment]
Categorised the requirements into those that are awaiting a decision, and those that require an implementation

**Comment by paulb-elastic** [comment]
Added the requirement to change the behaviour such that the Synthetic Agent does not capture filmstrip images by default, but enable them via a feature flag/configuration (https://github.com/elastic/synthetics/issues/143)

**Comment by paulb-elastic** [comment]
Modified the link to refer to https://github.com/elastic/uptime-dev/issues/32 which replaces https://github.com/elastic/uptime-dev/issues/31

**Comment by paulb-elastic** [comment]
Moved #144 from beta to GA deliverable

**Comment by paulb-elastic** [comment]
As per this [discussion](https://github.com/elastic/uptime-dev/issues/32#issuecomment-738829116), we are moving the bigger security changes https://github.com/elastic/uptime-dev/issues/32 from [beta](https://github.com/elastic/synthetics/issues/61) to [GA](https://github.com/elastic/synthetics/issues/93), but adding the sandbox option ([synthetics implementation](https://github.com/elastic/synthetics/issues/136), [heartbeat implementation](https://github.com/elastic/beats/issues/22901)) as a [beta requirement](https://github.com/elastic/synthetics/issues/61).

**Comment by paulb-elastic** [comment]
Added https://github.com/elastic/synthetics/issues/185 to the scope of beta

**Comment by paulb-elastic** [comment]
Added https://github.com/elastic/synthetics/issues/191 as a beta requirement

**Comment by vigneshshanmugam** [comment]
Adding https://github.com/elastic/synthetics/issues/172 as a beta requirement as its a bug and happens for all suites that are run as TS files.

**Comment by paulb-elastic** [comment]
Moving [remote ZIP support](https://github.com/elastic/uptime/issues/271) from being in [GA](https://github.com/elastic/synthetics/issues/93) to be in for [beta](https://github.com/elastic/synthetics/issues/61)

**Comment by paulb-elastic** [comment]
The above change of scope has been reverted.  [Remote Zip URL support for heartbeat synthetics](https://github.com/elastic/uptime/issues/271) has been taken out of this (beta) and added back into [GA](https://github.com/elastic/synthetics/issues/93).

**Comment by paulb-elastic** [comment]
https://github.com/elastic/uptime/issues/271 made beta, so added back into here

**Comment by vigneshshanmugam** [comment]
`package.json` docs are here - https://discuss.elastic.co/t/synthetics-1-0-0-beta-0-breaking-changes/271118
