### ISSUE TITLE
[META] Synthetics GA Release (WIP)

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#93]
# TODOs for synthetics GA

Listed roughly in order of priority

## Features

- [x] Synthetics ECommerce full-featured demo - https://github.com/vigneshshanmugam/synthetics-ecommerce-demo
- [ ] Release Synthetics as package version 1.0.0 https://github.com/elastic/synthetics-dev/issues/184
- [x] De-duplicate screenshots https://github.com/elastic/synthetics/issues/285 https://github.com/elastic/kibana/issues/100474
- [x] Fleet Integration can detect whether agents have synthetics capability (and warn about it) https://github.com/elastic/beats/issues/25775
- [x] Add `--rich-metadata` flag https://github.com/elastic/synthetics/issues/289
- [x] Propagate errors from beforeAll and afterAll hooks https://github.com/elastic/synthetics/issues/280
- [x] Add opinionated assertion functions https://github.com/elastic/synthetics/issues/201
- [x] Add tags/filtering https://github.com/elastic/synthetics/issues/26 https://github.com/elastic/beats/issues/26747
- [x] Capture relevant perf metrics to close the gap with RUM agent https://github.com/elastic/synthetics/issues/120
- [x] Support `ignoreHTTPSErrors` option for playwright (needs heartbeat option, should be flag)
- [x] Limit the number of suites in HB - https://github.com/elastic/beats/issues/23216
- [x] Improve mappings for addl metrics https://github.com/elastic/synthetics/issues/303
- [x] Add step duration as indexed field https://github.com/elastic/synthetics/issues/302
- [x] Update core vitals CLS definition https://github.com/elastic/synthetics/issues/301
- [x] Add support for browser/context options to config https://github.com/elastic/synthetics/issues/299
- [x] Remove -e flag in favor of NODE_ENV elastic/synthetics#318 
- [x] Step Level tracing #358 
- [x] Use network events from playwright session over CDP https://github.com/elastic/synthetics/issues/287
- [x] Synthetics node integration is ready https://github.com/elastic/uptime/issues/441

## CI Related
- [x] Add snyk to builds https://github.com/elastic/observability-robots/issues/246

## Docs related
- [x] Add pure JS examples https://github.com/elastic/synthetics/issues/105
- [x] Document how to retain data with fleet integration and ILM policies https://github.com/elastic/synthetics/issues/286
- [ ] Docs around consistent system perf for consistent tests
- [x] Docs around passing custom options to Synthetics Suites - https://github.com/elastic/observability-docs/pull/847
- [ ] Update support matrix https://github.com/elastic/synthetics/issues/392

## Stretch (non-blockers for GA, but nice to have)

- [x] Clean up params flags / naming https://github.com/elastic/synthetics/issues/288
- [x] Support for `push` https://github.com/elastic/synthetics/issues/494
- [x] Sensible defaults for network throttling https://github.com/elastic/synthetics/issues/284
- [x] Add support for max concurrent journeys to heartbeat https://github.com/elastic/beats/issues/23216
- [x] Elastic Synthetic Identifier In UA String https://github.com/elastic/synthetics/issues/232
- ~~[ ] Simplify process for adding custom CAs https://github.com/elastic/synthetics/issues/170~~
- ~~[ ] Screenshot images may not be correct dimensions https://github.com/elastic/synthetics/issues/371~~

**Comment by paulb-elastic** [comment]
Moved #144 from beta to GA deliverable

**Comment by paulb-elastic** [comment]
As per this [discussion](https://github.com/elastic/uptime-dev/issues/32#issuecomment-738829116), we are moving the bigger security changes https://github.com/elastic/uptime-dev/issues/32 from [beta](https://github.com/elastic/synthetics/issues/61) to [GA](https://github.com/elastic/synthetics/issues/93), but adding the sandbox option ([synthetics implementation](https://github.com/elastic/synthetics/issues/136), [heartbeat implementation](https://github.com/elastic/beats/issues/22901)) as a [beta requirement](https://github.com/elastic/synthetics/issues/61).

**Comment by paulb-elastic** [comment]
Added [Elastic Synthetic Identifier In UA String](https://github.com/elastic/synthetics/issues/232) to the scope for GA

**Comment by paulb-elastic** [comment]
Moving [remote ZIP support](https://github.com/elastic/uptime/issues/271) from being in [GA](https://github.com/elastic/synthetics/issues/93) to be in for [beta](https://github.com/elastic/synthetics/issues/61)

**Comment by paulb-elastic** [comment]
Added https://github.com/elastic/synthetics/issues/280

**Comment by paulb-elastic** [comment]
Added https://github.com/elastic/synthetics/issues/371 to stretch goals

**Comment by vigneshshanmugam** [comment]
Moved #287 to features list as popups are key part in page journeys and should be handled before going GA.
